# Copyright (c) 2019-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: rmm
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=rmm-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=rmm-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - cmake >=3.23.1,!=3.25.0
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if cuda_major == "12" %}
    - {{ compiler('cuda12') }} {{ cuda_version }}
    - cuda-cudart ={{ cuda_version }}
    - cuda-cudart-dev ={{ cuda_version }}
    - cuda-cudart-static ={{ cuda_version }}
    {% else %}
    - {{ compiler('cuda11') }} {{ cuda_version }}
    {% endif %}

    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    {% if cuda_major == "12" %}
    - cuda-nvcc ={{ cuda_version }}
    - cuda-cudart ={{ cuda_version }}
    - cuda-cudart-dev ={{ cuda_version }}
    - cuda-cudart-static ={{ cuda_version }}
    - cuda-python >=12.1,<13.0
    {% else %}
    - cudatoolkit ={{ cuda_version }}
    - cuda-python >=11.7.1,<12.0
    {% endif %}
    - cython >=0.29,<0.30
    - librmm ={{ version }}
    - python
    - scikit-build >=0.13.1
    - setuptools >=61.0.0
    - tomli  # [py<311]
  run:
    {% if cuda_major == "12" %}
    - cuda-python >=12.1,<13.0
    - cuda-cudart ={{ cuda_version }}
    {% else %}
    - cuda-python >=11.7.1,<12.0
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    {% endif %}
    - numba >=0.49
    - numpy >=1.19

test:
  imports:
    - rmm

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rmm library
